-- Rubber Requiem Supabase schema.
-- Run once in Supabase SQL Editor. Safe to re-run.

create table if not exists public.leaderboards (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 18),
  score bigint not null check (score >= 0),
  mode text not null check (char_length(mode) between 1 and 24),
  character text not null check (char_length(character) between 1 and 32),
  weapon text not null check (char_length(weapon) between 1 and 32),
  kills integer not null default 0 check (kills >= 0),
  waves integer not null default 0 check (waves >= 0),
  coins_earned integer not null default 0 check (coins_earned >= 0),
  daily_seed bigint,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.player_profiles (
  player_name text primary key check (char_length(player_name) between 1 and 18),
  total_coins bigint not null default 50 check (total_coins >= 0),
  lifetime_coins bigint not null default 50 check (lifetime_coins >= 0),
  total_runs integer not null default 0 check (total_runs >= 0),
  total_kills integer not null default 0 check (total_kills >= 0),
  high_score bigint not null default 0 check (high_score >= 0),
  unlocked_weapons text[] not null default array[]::text[],
  achievements text[] not null default array[]::text[],
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.coin_history (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 18),
  amount integer not null check (amount <> 0),
  source text not null check (char_length(source) between 1 and 32),
  description text not null check (char_length(description) between 1 and 160),
  created_at timestamptz not null default timezone('utc', now())
);

-- These match the app's two bounded reads and avoid maintaining redundant indexes.
create index if not exists leaderboards_mode_score_idx
  on public.leaderboards (mode, score desc);
create index if not exists leaderboards_daily_score_idx
  on public.leaderboards (daily_seed, score desc)
  where daily_seed is not null;
create index if not exists coin_history_player_created_idx
  on public.coin_history (player_name, created_at desc);

alter table public.leaderboards enable row level security;
alter table public.player_profiles enable row level security;
alter table public.coin_history enable row level security;

-- The game intentionally supports anonymous nickname-based play. Leaderboards,
-- profiles, and the nickname-based ledger are therefore public to the anon role;
-- application-side nickname validation keeps the payloads bounded.
drop policy if exists "Allow public read on leaderboards" on public.leaderboards;
drop policy if exists "Allow public insert on leaderboards" on public.leaderboards;
create policy "Allow public read on leaderboards"
  on public.leaderboards for select to anon, authenticated using (true);
create policy "Allow public insert on leaderboards"
  on public.leaderboards for insert to anon, authenticated with check (
    char_length(player_name) between 1 and 18
    and score >= 0 and kills >= 0 and waves >= 0 and coins_earned >= 0
  );

drop policy if exists "Allow public read on player_profiles" on public.player_profiles;
drop policy if exists "Allow public insert on player_profiles" on public.player_profiles;
drop policy if exists "Allow public update on player_profiles" on public.player_profiles;
create policy "Allow public read on player_profiles"
  on public.player_profiles for select to anon, authenticated using (
    char_length(player_name) between 1 and 18
  );
create policy "Allow public insert on player_profiles"
  on public.player_profiles for insert to anon, authenticated with check (
    char_length(player_name) between 1 and 18 and total_coins >= 0 and lifetime_coins >= 0
  );
create policy "Allow public update on player_profiles"
  on public.player_profiles for update to anon, authenticated using (
    char_length(player_name) between 1 and 18
  ) with check (
    char_length(player_name) between 1 and 18 and total_coins >= 0 and lifetime_coins >= 0
  );

drop policy if exists "Allow public read on coin_history" on public.coin_history;
drop policy if exists "Allow public insert on coin_history" on public.coin_history;
create policy "Allow public read on coin_history"
  on public.coin_history for select to anon, authenticated using (
    char_length(player_name) between 1 and 18
  );
create policy "Allow public insert on coin_history"
  on public.coin_history for insert to anon, authenticated with check (
    char_length(player_name) between 1 and 18
    and char_length(description) between 1 and 160
    and amount <> 0
  );
